name = "stems"
route = "stems.audius.co/*"

type = "webpack"
account_id = "3811365464a8e56b2b27a5590e328e49"
workers_dev = true

[site]
bucket = "./storybook-static"
entry-point = "./scripts/workers-site"
