web-pr-comment:
  parameters:
    comment:
      description: The comment to add to the PR
      type: string
    maxComments:
      default: 1
      description: Max nb of comments per PR
      type: integer
    pr:
      default: $CIRCLE_PULL_REQUEST
      description: The PR number or URL
      type: string
  steps:
    - run:
        command: |
          sudo apt-get update
          sudo apt-get install -y --force-yes ruby-full
        name: Install Ruby
    - run:
        command: |
          curl -sL https://raw.githubusercontent.com/stephencelis/ghi/master/ghi > ghi
          chmod 755 ghi
          sudo mv ghi /usr/local/bin
        name: Install GHI
    - run:
        command: |
          if [[ -z "${GHI_TOKEN}" ]]; then
            echo "GHI_TOKEN not set"
            /bin/false
          fi
        name: Check Token
    - run:
        command: |
          GH_LOGIN=$(curl -sS https://api.github.com/user\?access_token\=$GHI_TOKEN | jq '.login' --raw-output)
          echo "Authenticated with $GH_LOGIN"
          PR_URL=<< parameters.pr >>
          PR_ID=${PR_URL##*/}
          echo "PR_ID=$PR_ID"
          if [ -z $PR_ID ]; then
            echo "No PR found, skipping"
          else
            if [ $(ghi comment --list $PR_ID | grep -c $GH_LOGIN) -ge << parameters.maxComments >> ]; then
              echo "Already commented, skip"
            else
              ghi comment -m "<< parameters.comment >>"  $PR_ID
            fi
          fi
        name: Send Comment

web-build:
  parameters:
    build-type:
      default: "prod-source-maps"
      type: string
    build-directory:
      default: "packages/web/build-production"
      type: string
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: build
        command: |
          cd packages/web
          CI=false npm run build:<< parameters.build-type >>
    - persist_to_workspace:
        root: ./
        paths:
          - << parameters.build-directory >>

web-distribute:
  parameters:
    build-type:
      default: "mac-publish-production"
      type: string
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: distribute
        command: |
          cd packages/web
          npm run dist:<< parameters.build-type >>

web-install-awscli:
  steps:
    - run:
        name: install-awscli
        command: sudo pip install awscli

web-install-wrangler:
  steps:
    - run:
        name: install wrangler
        command: "cd packages/web && npm install @cloudflare/wrangler"

web-deploy-cloudflare:
  parameters:
    build-type:
      default: "production"
      type: string
    environment:
      default: "production"
      type: string
    copy-robots:
      default: false
      type: boolean
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - web-install-wrangler
    - run:
        name: Set up workers site
        command: |
          cd packages/web/scripts/workers-site
          npm i
          cd ../../
          mv build-<< parameters.build-type >> build
    - run:
        name: Copy robots.txt
        command: |
          cd packages/web
          cp ./robots.txt build
    - run:
        name: Deploy to Cloudflare
        command: |
          cd packages/web
          echo ${GA_ACCESS_TOKEN} | npx wrangler secret put GA_ACCESS_TOKEN --env << parameters.environment >>
          npx wrangler publish --env << parameters.environment >>

web-deploy-ipfs:
  parameters:
    build-type:
      default: "production"
      type: string
  steps:
    - web-install-awscli
    - attach_workspace:
        at: ./
    - run:
        name: Deploy to S3
        command: aws s3 cp packages/web/build-ipfs-<< parameters.build-type >>.zip s3://audius-site-ipfs/build-ipfs-<< parameters.build-type >>.zip

web-update-ga-ipfs-build:
  parameters:
    build-type:
      default: "prod"
      type: string
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: Update ipfs build in ga
        command: |
          cd packages/web
          npm run update-ipfs-build:<< parameters.build-type >>
    - persist_to_workspace:
        root: ./
        paths:
          - ./packages/web/build_cid.txt

web-publish-build-cids:
  parameters:
    build-type:
      default: "production"
      type: string
  steps:
    - web-install-awscli
    - attach_workspace:
        at: ./
    - run:
        name: Push to S3
        command: aws s3 cp packages/web/build_cid.txt s3://audius-site-ipfs/build_cid_<< parameters.build-type >>.txt

web-update-ipfs-records:
  parameters:
    dns-name:
      default: "_dnslink.ipfs.audius.co"
      type: string
    dns-id:
      default: "${CLOUDFLARE_PROD_SITE_IPFS_DNS_ID}"
      type: string
  steps:
    - attach_workspace:
        at: ./
    - run:
        name: Update Cloudflare records
        command: |
          DNS_NAME=<< parameters.dns-name >>
          CID=$(cat ./packages/web/build_cid.txt)
          curl -X PUT "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_AUDIUS_CO_ZONE}/dns_records/<< parameters.dns-id >>" \
            -H "X-Auth-Email: ${CLOUDFLARE_AUTH_EMAIL}" \
            -H "Authorization: Bearer ${CLOUDFLARE_AUTH_KEY}" \
            -H "Content-Type: application/json" \
            --data '{"type":"TXT","name":"'"$DNS_NAME"'","content":"\"dnslink=/ipfs/'"$CID"'\"","ttl":1,"proxied":false}'
