// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const bottomSection: string;
export const artworkStyle: string;
export const scrubber: string;
export const playButton: string;
export const shareWrapper: string;
