// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const albumArt: string;
export const trackInfo: string;
export const topSection: string;
export const bottomSection: string;
export const titles: string;
export const title: string;
export const handle: string;
export const shareButton: string;
