// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const trackInfo: string;
export const topSection: string;
export const bottomSection: string;
export const shareButton: string;
export const logo: string;
export const shareButtonHolder: string;
export const titleContainer: string;
