type = "webpack"
account_id = "3811365464a8e56b2b27a5590e328e49"
workers_dev = true

[site]
bucket = "./build"
entry-point = "./scripts/workers-site"

[env.staging]
name = "audius-staging"
vars = { ENVIRONMENT = "staging", GA = "https://general-admission.staging.audius.co", DISCOVERY_NODES = "https://discoveryprovider.staging.audius.co,https://discoveryprovider2.staging.audius.co,https://discoveryprovider3.staging.audius.co,https://discoveryprovider5.staging.audius.co" }

[env.staging-release]
name = "audius-staging-release-candidate"
vars = { ENVIRONMENT = "staging", GA = "https://general-admission.staging.audius.co", DISCOVERY_NODES = "https://discoveryprovider.staging.audius.co,https://discoveryprovider2.staging.audius.co,https://discoveryprovider3.staging.audius.co,https://discoveryprovider5.staging.audius.co" }

[env.release]
name = "audius-release-candidate"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.audius.co", DISCOVERY_NODES = "https://discoveryprovider.audius.co,https://discoveryprovider2.audius.co,https://discoveryprovider3.audius.co" }

[env.production]
name = "audius"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.audius.co", DISCOVERY_NODES = "https://discoveryprovider.audius.co,https://discoveryprovider2.audius.co,https://discoveryprovider3.audius.co" }

# Test environment, replace `test` with subdomain
# Invoke with npx wrangler preview --watch --env test
[env.test]
name = "test"
vars = { ENVIRONMENT = "production", GA = "https://general-admission.audius.co", DISCOVERY_NODES = "https://discoveryprovider.audius.co,https://discoveryprovider2.audius.co,https://discoveryprovider3.audius.co" }