when: << pipeline.parameters.run-mobile-workflow >>
jobs:
  - mobile-init:
      context: Audius Mobile Client

  - mobile-build-upload-staging-ios:
      context: Audius Mobile Client
      requires:
        - mobile-init

  - mobile-build-upload-releasecandidate-ios:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^release.*)$/

  - mobile-build-upload-staging-releasecandidate-ios:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^release.*)$/

  - mobile-build-upload-production-ios:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^main|^release.*)$/

  - mobile-build-upload-staging-android:
      context: Audius Mobile Client
      requires:
        - mobile-init

  - mobile-build-upload-releasecandidate-android:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^release.*)$/

  - mobile-build-upload-staging-releasecandidate-android:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^release.*)$/

  - mobile-build-upload-production-android:
      context: Audius Mobile Client
      requires:
        - mobile-init
      filters:
        branches:
          only: /(^main|^release.*)$/
