when: << pipeline.parameters.run-mobile-workflow >>
jobs:
  - mobile-init:
      context: Audius Mobile Client

  - mobile-build-upload-staging-ios:
      context: Audius Mobile Client

  - mobile-build-upload-staging-android:
      context: Audius Mobile Client

  - mobile-build-upload-production-ios:
      context: Audius Mobile Client
      filters:
        branches:
          only: /(^main|^release.*)$/

  - mobile-build-upload-production-android:
      context: Audius Mobile Client
      filters:
        branches:
          only: /(^main|^release.*)$/
