jobs:
  - root-hold-publish-npm-packages:
      context: Audius Client
      type: approval
      filters:
        branches:
          only: /(^release.*)$/
  - root-publish-npm-packages:
      context: Audius Client
      requires:
        - root-hold-publish-npm-packages
      filters:
        branches:
          only: /(^release.*)$/
  - root-publish-github-release:
      context: Audius Client
      filters:
        branches:
          only: /(^release.*)$/
