when: << pipeline.parameters.run-stems-workflow >>
jobs:
  - stems-init
  - stems-build-storybook:
      requires:
        - stems-init
  - stems-deploy-storybook:
      context: Audius Client
      requires:
        - stems-build-storybook
