when: << pipeline.parameters.run-stems-workflow >>
jobs:
  - stems-init
  - stems-build-storybook:
      requires:
        - stems-init
      filters:
        branches:
          only: /^nkang--lint-stems$/
  - stems-deploy-storybook:
      context: Audius Client
      requires:
        - stems-build-storybook
      filters:
        branches:
          only: /^nkang--lint-stems$/
