version: 2.1

orbs:
  ruby: circleci/ruby@1.2.0
  cypress: cypress-io/cypress@3.0.0
  macos: circleci/macos@2

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb in config.yml
parameters:
  run-web-workflow:
    type: boolean
    default: false
  run-mobile-workflow:
    type: boolean
    default: false
  run-stems-workflow:
    type: boolean
    default: false
# Can enable recurring probers against stage at some point
# workflows:
#   version: 2.1
#   hourly:
#     triggers:
#       - schedule:
#           cron: '17 * * * *'
#           filters:
#             branches:
#               only:
#                 - main
#     jobs:
#       - probers-test-stage
