embed-init:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout

    - create_concatenated_package_lock:
        filename: combined-package-lock.txt

    - create_concatenated_patch_file:
        filename: combined-patch-file.txt

    - restore_cache:
        keys:
          - cache-{{ checksum "package-lock.json" }}-{{ checksum "combined-package-lock.txt" }}-{{ checksum "combined-patch-file.txt" }}

    - restore_cache:
        keys:
          - cache-{{ .Revision }}

    - run:
        name: Link packages
        command: |
          npm run link

    - persist_to_workspace:
        root: ./
        paths:
          - node_modules
          - packages/embed/node_modules
          - packages/stems/node_modules
          - packages/stems/dist


embed-build-staging:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - embed-build:
        build-directory: packages/embed/build-staging
        build-type: stage


embed-build-production:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  resource_class: xlarge
  steps:
    - embed-build:
        build-directory: packages/embed/build-production
        build-type: prod


embed-deploy-staging-cloudflare:
  working_directory: ~/audius-client
  docker:
    - image: cimg/python:3.7.12-node
  steps:
    - embed-deploy-cloudflare:
        build-type: staging
        environment: staging


embed-deploy-production-cloudflare:
  working_directory: ~/audius-client
  docker:
    - image: cimg/python:3.7.12-node
  steps:
    - embed-deploy-cloudflare:
        build-type: production
        environment: production
