mobile-init:
  working_directory: ~/audius-client
  docker:
    - image: cimg/node:18.17
  steps:
    - checkout
    - run:
        name: copy staging env
        command: |
          cd packages/mobile
          echo "FCM_SENDER_ID=$FCM_SENDER_ID" >> .env.stage
          echo "AMPLITUDE_WRITE_KEY=$AMPLITUDE_WRITE_KEY_STAGE" >> .env.stage
    - run:
        name: copy production env
        command: |
          cd packages/mobile
          echo "FCM_SENDER_ID=$FCM_SENDER_ID" >> .env.prod
          echo "AMPLITUDE_WRITE_KEY=$AMPLITUDE_WRITE_KEY_PROD" >> .env.prod

    - create_concatenated_patch_file:
        filename: combined-patch-file.txt

    - restore_cache:
        keys:
          - cache-{{ checksum "package-lock.json" }}-{{ checksum "combined-patch-file.txt" }}

    - restore_cache:
        keys:
          - cache-{{ .Revision }}

    - common-lint

    - run:
        name: typecheck
        command: cd packages/mobile && npm run typecheck

    - run:
        name: lint
        command: cd packages/mobile && npm run lint

    - persist_to_workspace:
        root: ./
        paths:
          - node_modules
          - packages/web/node_modules
          - packages/mobile/node_modules
          - packages/stems/node_modules
          - packages/stems/dist
          - packages/common/node_modules
          - packages/common/dist
          - packages/mobile/.env.stage
          - packages/mobile/.env.prod

mobile-comment-native-code-change:
  working_directory: ~/audius-client
  docker:
    - image: cimg/node:14.20
  steps:
    - checkout
    - mobile-halt-if-no-native-changes
    - web-pr-comment:
        comment: 'It looks like there may be some changes to native mobile code, which requires triggering a full app release. Please follow the instructions here: https://www.notion.so/audiusproject/When-to-bump-app-version-2644a8f772364a4d91f44abcba44ce0b?pvs=4. cc @nicoback2 @sliptype'

mobile-build-staging-ios:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - mobile-halt-if-no-native-changes # Don't need to test building if there's no native changes
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - run:
        name: Install Sentry CLI
        command: curl -sL https://sentry.io/get-cli/ | bash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-staging'
        bundle-id: 'co.audius.audiusmusic.staging'
        env: '.env.stage'
    - mobile-build-ios:
        build-directory: 'build-mobile-staging'
        bundle-id: 'co.audius.audiusmusic.staging'
        env: '.env.stage'

mobile-build-upload-staging-ios:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - mobile-prepare-ios:
        build-directory: 'build-mobile-staging'
        bundle-id: 'co.audius.audiusmusic.staging'
        env: '.env.stage'
    - mobile-release-ios:
        build-directory: 'build-mobile-staging'
        bundle-id: 'co.audius.audiusmusic.staging'
        env: '.env.stage'

mobile-build-production-ios:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'
    - mobile-build-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'

mobile-build-upload-production-ios-if-full-release:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'
    - mobile-halt-if-codepush-release-ios
    - mobile-release-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'

mobile-deploy-codepush-production-ios-if-ota-release:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'
    - mobile-release-ios:
        build-directory: 'build-mobile-production'
        bundle-id: 'co.audius.audiusmusic'
        env: '.env.prod'

mobile-build-upload-releasecandidate-ios:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-releasecandidate'
        bundle-id: 'co.audius.audiusmusic.releasecandidate'
        env: '.env.prod'
    - mobile-release-ios:
        build-directory: 'build-mobile-releasecandidate'
        bundle-id: 'co.audius.audiusmusic.releasecandidate'
        env: '.env.prod'

mobile-build-upload-staging-releasecandidate-ios:
  working_directory: ~/audius-client
  # run on macos so app can be created and signed.
  resource_class: macos.x86.medium.gen2
  macos:
    xcode: '14.2.0'
  environment:
    FL_OUTPUT_DIR: output
  shell: /bin/bash --login -o pipefail
  steps:
    - run:
        name: Set Ruby Version
        command: rbenv global 2.7.7 && rbenv rehash
    - mobile-prepare-ios:
        build-directory: 'build-mobile-staging-releasecandidate'
        bundle-id: 'co.audius.audiusmusic.staging.releasecandidate'
        env: '.env.prod'
    - mobile-release-ios:
        build-directory: 'build-mobile-staging-releasecandidate'
        bundle-id: 'co.audius.audiusmusic.staging.releasecandidate'
        env: '.env.prod'

mobile-build-staging-android:
  working_directory: ~/audius-client
  resource_class: xlarge
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-staging'
    - mobile-build-android:
        build-directory: 'build-mobile-staging'
        build-type: 'bundleStagingRelease'
        bundle-id: 'co.audius.app.staging'
        track: 'internal'
        remote-directory: 'audius-mobile-staging'

mobile-build-upload-staging-android:
  working_directory: ~/audius-client
  resource_class: xlarge
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-staging'
    - mobile-release-android:
        build-directory: 'build-mobile-staging'
        upload-type: 'staging'
        track: 'internal'

mobile-build-upload-staging-releasecandidate-android:
  working_directory: ~/audius-client
  resource_class: large
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-staging-releasecandidate'
    - mobile-release-android:
        build-directory: 'build-mobile-staging-releasecandidate'
        upload-type: 'stagingReleaseCandidate'
        track: 'internal'

mobile-build-upload-releasecandidate-android:
  working_directory: ~/audius-client
  resource_class: large
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-releasecandidate'
    - mobile-release-android:
        build-directory: 'build-mobile-releasecandidate'
        upload-type: 'releaseCandidate'
        track: 'internal'

mobile-build-production-android:
  working_directory: ~/audius-client
  resource_class: xlarge
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-production'
    - mobile-build-android:
        build-directory: 'build-mobile-production'
        build-type: 'bundleRelease'
        bundle-id: 'co.audius.app'
        track: 'alpha'
        remote-directory: 'audius-mobile'

mobile-build-upload-production-android-if-full-release:
  working_directory: ~/audius-client
  resource_class: xlarge
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-production'
    - mobile-halt-if-codepush-release-android
    - mobile-release-android:
        build-directory: 'build-mobile-production'
        upload-type: 'prod'
        track: 'alpha'

mobile-deploy-codepush-production-android-if-ota-release:
  working_directory: ~/audius-client
  resource_class: large
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-production'
    - mobile-release-android:
        build-directory: 'build-mobile-production'
        upload-type: 'prod'
        track: 'alpha'

mobile-deploy-saga-dapp-store:
  working_directory: ~/audius-client
  resource_class: xlarge
  docker:
    - image: cimg/android:2023.08-node
  steps:
    - mobile-prepare-android:
        build-directory: 'build-mobile-production'
    - mobile-release-saga-dapp-store:
        bundle-id: 'co.audius.app'
        track: 'alpha'
