# Publish npm packages
root-publish-npm-packages:
  working_directory: ~/audius-client
  docker:
    - image: circleci/node:14.18
  steps:
    - checkout
    - run:
        name: npm Auth
        command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
    - run:
        name: Publish packages
        command: npx lerna publish from-git --yes

# Publish github release for the current tag
root-publish-github-release:
  working_directory: ~/audius-client
  docker:
    - image: cibuilds/github:0.10
  steps:
    - checkout
    - attach_workspace:
        at: ./
    - run:
        name: "Publish Release on GitHub"
        command: |
          VERSION=$(grep -m1 version ./lerna.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
          CHANGELOG=$(git log --format=%B -n 1)
          ghr -t ${GHI_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -b "${CHANGELOG}" v${VERSION} ./
