// This file is automatically generated from your CSS. Any edits will be overwritten.
export const container: string;
export const logo: string;
export const artwork: string;
export const artworkSizing: string;
export const dismissIcon: string;
export const label: string;
