import { resolve } from "path";
import envVars from "preact-cli-plugin-env-vars";

export default function(config, env, helpers) {
  // Switch css-loader for typings-for-css-modules-loader, which is a wrapper
  // that automatically generates .d.ts files for loaded CSS
  helpers.getLoadersByName(config, "css-loader").forEach(({ loader }) => {
    loader.loader = "typings-for-css-modules-loader";
    loader.options = Object.assign(loader.options, {
      camelCase: true,
      banner:
        "// This file is automatically generated from your CSS. Any edits will be overwritten.",
      namedExport: true,
      silent: true
    });
  });

  // Use any `index` file, not just index.js
  config.resolve.alias["preact-cli-entrypoint"] = resolve(
    process.cwd(),
    "src",
    "index"
  );

  // Inject env vars
  envVars(config, env, helpers);

  // Set relative imports
  // https://github.com/preactjs/preact-cli/issues/279
  config.output.publicPath = "./";

  return config;
}
