version: 2.1
jobs:
  coverage:
    working_directory: ~/probers
    docker:
      - image: circleci/node:14.18-browsers
    resource_class: large
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - probers-dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - probers-dependency-cache-
      - run:
          name: install probers dependencies
          command: |
            npm install
      - save_cache:
          key: probers-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run prober tests
          command: |
            npm run test:ci

  pings:
    working_directory: ~/probers
    docker:
      - image: circleci/node:14.18-browsers
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - probers-dependency-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - probers-dependency-cache-
      - run:
          name: install probers dependencies
          command: |
            npm install
      - save_cache:
          key: probers-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: run prober pings
          command: |
            npm run pings

workflows:
  version: 2
  commit:
    jobs:
      - coverage
  hourly:
    triggers:
      - schedule:
          cron: "17 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - coverage
  hourly_pings:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pings


