version: 2.1
jobs:
  download-dapp:
    working_directory: ~/probers
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: install-awscli
          command: sudo pip install awscli
      - run:
          name: Download Dapp from S3
          command: | 
            cd ../
            aws s3 sync s3://app.staging.audius.co ./dapp
      - persist_to_workspace:
          root: ./
          paths:
            - dapp
            - probers

  coverage:
    working_directory: ~/
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - attach_workspace:
          at: ./
      # Download and cache dependencies
      - restore_cache:
          keys:
            - probers-dependency-cache-{{ checksum "probers/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - probers-dependency-cache-
      - run:
          name: install probers dependencies
          command: |
            cd probers
            npm install
      - save_cache:
          key: probers-dependency-cache-{{ checksum "probers/package.json" }}
          paths:
            - ./probers/node_modules
      - run:
          name: serve and run prober tests
          command: |
            npm install serve
            node node_modules/serve/bin/serve.js -l 3000 -s dapp &
            cd probers
            npm test

workflows:
  version: 2
  commit:
    jobs:
      - download-dapp
      - coverage:
          requires:
            - download-dapp
  nightly:
    triggers:
      - schedule:
        cron: "0 4 * * *"
        filters:
          branches:
            only:
              - master
              - beta
    jobs:
      - download-dapp
      - coverage:
          requires:
            - download-dapp


